apiVersion: v1
kind: Pod
metadata:
  name: prototype
spec:
  containers:
  - name: prototype
    image: gcr.io/priya-wadhwa/prototype:latest
    volumeMounts:
    - name: kaniko-secret
      mountPath: /secret
    env:
      - name: GOOGLE_APPLICATION_CREDENTIALS
        value: /secret/priya-wadhwa-07f2d891ee9f.json
  serviceAccountName: prototype-service-account
  restartPolicy: Never
  volumes:
    - name: kaniko-secret
      secret:
        secretName: kaniko-secret
