apiVersion: v1
kind: Pod
metadata:
  name: prototype
spec:
  containers:
  - name: prototype
    image: gcr.io/priya-wadhwa/prototype:latest
    volumeMounts:
    - name: priyawadhwa-ca-admin
      mountPath: /secret
    env:
      - name: GOOGLE_APPLICATION_CREDENTIALS
        value: /secret/priyawadhwa-ca-admin.json
  serviceAccountName: prototype-service-account
  restartPolicy: Never
  volumes:
    - name: priyawadhwa-ca-admin
      secret:
        secretName: priyawadhwa-ca-admin


