/*
Copyright 2018 Google LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1beta1

import (
	time "time"

	grafeasprototype_v1beta1 "github.com/priyawadhwa/grafeasprototype/pkg/apis/grafeasprototype/v1beta1"
	versioned "github.com/priyawadhwa/grafeasprototype/pkg/client/clientset/versioned"
	internalinterfaces "github.com/priyawadhwa/grafeasprototype/pkg/client/informers/externalversions/internalinterfaces"
	v1beta1 "github.com/priyawadhwa/grafeasprototype/pkg/client/listers/grafeasprototype/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ImagePolicyRequirementInformer provides access to a shared informer and lister for
// ImagePolicyRequirements.
type ImagePolicyRequirementInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1beta1.ImagePolicyRequirementLister
}

type imagePolicyRequirementInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewImagePolicyRequirementInformer constructs a new informer for ImagePolicyRequirement type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewImagePolicyRequirementInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredImagePolicyRequirementInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredImagePolicyRequirementInformer constructs a new informer for ImagePolicyRequirement type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredImagePolicyRequirementInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.GrafeasprototypeV1beta1().ImagePolicyRequirements(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.GrafeasprototypeV1beta1().ImagePolicyRequirements(namespace).Watch(options)
			},
		},
		&grafeasprototype_v1beta1.ImagePolicyRequirement{},
		resyncPeriod,
		indexers,
	)
}

func (f *imagePolicyRequirementInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredImagePolicyRequirementInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *imagePolicyRequirementInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&grafeasprototype_v1beta1.ImagePolicyRequirement{}, f.defaultInformer)
}

func (f *imagePolicyRequirementInformer) Lister() v1beta1.ImagePolicyRequirementLister {
	return v1beta1.NewImagePolicyRequirementLister(f.Informer().GetIndexer())
}
