// +build !ignore_autogenerated

/*
Copyright 2018 Google LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1beta1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImagePolicyRequirement) DeepCopyInto(out *ImagePolicyRequirement) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImagePolicyRequirement.
func (in *ImagePolicyRequirement) DeepCopy() *ImagePolicyRequirement {
	if in == nil {
		return nil
	}
	out := new(ImagePolicyRequirement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ImagePolicyRequirement) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImagePolicyRequirementList) DeepCopyInto(out *ImagePolicyRequirementList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ImagePolicyRequirement, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImagePolicyRequirementList.
func (in *ImagePolicyRequirementList) DeepCopy() *ImagePolicyRequirementList {
	if in == nil {
		return nil
	}
	out := new(ImagePolicyRequirementList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ImagePolicyRequirementList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImagePolicyRequirementSpec) DeepCopyInto(out *ImagePolicyRequirementSpec) {
	*out = *in
	in.PackageVulernerabilityRequirements.DeepCopyInto(&out.PackageVulernerabilityRequirements)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImagePolicyRequirementSpec.
func (in *ImagePolicyRequirementSpec) DeepCopy() *ImagePolicyRequirementSpec {
	if in == nil {
		return nil
	}
	out := new(ImagePolicyRequirementSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PackageVulernerabilityRequirements) DeepCopyInto(out *PackageVulernerabilityRequirements) {
	*out = *in
	if in.Whitelist != nil {
		in, out := &in.Whitelist, &out.Whitelist
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PackageVulernerabilityRequirements.
func (in *PackageVulernerabilityRequirements) DeepCopy() *PackageVulernerabilityRequirements {
	if in == nil {
		return nil
	}
	out := new(PackageVulernerabilityRequirements)
	in.DeepCopyInto(out)
	return out
}
