apiVersion: v1
kind: ServiceAccount
metadata:
  name: prototype-service-account
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prototype-cluster-role
  labels:
    # Add these permissions to the "view" default role, so that "view" can see our CRD.
    rbac.authorization.k8s.io/aggregate-to-view: "true"
rules:
- apiGroups: ["grafeasprototype.github.com"] # API group created by crd
  resources: ["*"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: prototype
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
  - kind: ServiceAccount
    name: prototype-service-account
    namespace: default
