/*
Copyright 2018 Google LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1beta1 "github.com/priyawadhwa/kritis/pkg/apis/kritis/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeImagePolicyRequirements implements ImagePolicyRequirementInterface
type FakeImagePolicyRequirements struct {
	Fake *FakeKritisV1beta1
	ns   string
}

var imagepolicyrequirementsResource = schema.GroupVersionResource{Group: "kritis", Version: "v1beta1", Resource: "imagepolicyrequirements"}

var imagepolicyrequirementsKind = schema.GroupVersionKind{Group: "kritis", Version: "v1beta1", Kind: "ImagePolicyRequirement"}

// Get takes name of the imagePolicyRequirement, and returns the corresponding imagePolicyRequirement object, and an error if there is any.
func (c *FakeImagePolicyRequirements) Get(name string, options v1.GetOptions) (result *v1beta1.ImagePolicyRequirement, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(imagepolicyrequirementsResource, c.ns, name), &v1beta1.ImagePolicyRequirement{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.ImagePolicyRequirement), err
}

// List takes label and field selectors, and returns the list of ImagePolicyRequirements that match those selectors.
func (c *FakeImagePolicyRequirements) List(opts v1.ListOptions) (result *v1beta1.ImagePolicyRequirementList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(imagepolicyrequirementsResource, imagepolicyrequirementsKind, c.ns, opts), &v1beta1.ImagePolicyRequirementList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.ImagePolicyRequirementList{}
	for _, item := range obj.(*v1beta1.ImagePolicyRequirementList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested imagePolicyRequirements.
func (c *FakeImagePolicyRequirements) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(imagepolicyrequirementsResource, c.ns, opts))

}

// Create takes the representation of a imagePolicyRequirement and creates it.  Returns the server's representation of the imagePolicyRequirement, and an error, if there is any.
func (c *FakeImagePolicyRequirements) Create(imagePolicyRequirement *v1beta1.ImagePolicyRequirement) (result *v1beta1.ImagePolicyRequirement, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(imagepolicyrequirementsResource, c.ns, imagePolicyRequirement), &v1beta1.ImagePolicyRequirement{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.ImagePolicyRequirement), err
}

// Update takes the representation of a imagePolicyRequirement and updates it. Returns the server's representation of the imagePolicyRequirement, and an error, if there is any.
func (c *FakeImagePolicyRequirements) Update(imagePolicyRequirement *v1beta1.ImagePolicyRequirement) (result *v1beta1.ImagePolicyRequirement, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(imagepolicyrequirementsResource, c.ns, imagePolicyRequirement), &v1beta1.ImagePolicyRequirement{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.ImagePolicyRequirement), err
}

// Delete takes name of the imagePolicyRequirement and deletes it. Returns an error if one occurs.
func (c *FakeImagePolicyRequirements) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(imagepolicyrequirementsResource, c.ns, name), &v1beta1.ImagePolicyRequirement{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeImagePolicyRequirements) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(imagepolicyrequirementsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1beta1.ImagePolicyRequirementList{})
	return err
}

// Patch applies the patch and returns the patched imagePolicyRequirement.
func (c *FakeImagePolicyRequirements) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.ImagePolicyRequirement, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(imagepolicyrequirementsResource, c.ns, name, data, subresources...), &v1beta1.ImagePolicyRequirement{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.ImagePolicyRequirement), err
}
