/*
Copyright 2018 Google LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	v1beta1 "github.com/priyawadhwa/grafeasprototype/pkg/apis/grafeasprototype/v1beta1"
	scheme "github.com/priyawadhwa/grafeasprototype/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ImagePolicyRequirementsGetter has a method to return a ImagePolicyRequirementInterface.
// A group's client should implement this interface.
type ImagePolicyRequirementsGetter interface {
	ImagePolicyRequirements(namespace string) ImagePolicyRequirementInterface
}

// ImagePolicyRequirementInterface has methods to work with ImagePolicyRequirement resources.
type ImagePolicyRequirementInterface interface {
	Create(*v1beta1.ImagePolicyRequirement) (*v1beta1.ImagePolicyRequirement, error)
	Update(*v1beta1.ImagePolicyRequirement) (*v1beta1.ImagePolicyRequirement, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1beta1.ImagePolicyRequirement, error)
	List(opts v1.ListOptions) (*v1beta1.ImagePolicyRequirementList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.ImagePolicyRequirement, err error)
	ImagePolicyRequirementExpansion
}

// imagePolicyRequirements implements ImagePolicyRequirementInterface
type imagePolicyRequirements struct {
	client rest.Interface
	ns     string
}

// newImagePolicyRequirements returns a ImagePolicyRequirements
func newImagePolicyRequirements(c *GrafeasprototypeV1beta1Client, namespace string) *imagePolicyRequirements {
	return &imagePolicyRequirements{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the imagePolicyRequirement, and returns the corresponding imagePolicyRequirement object, and an error if there is any.
func (c *imagePolicyRequirements) Get(name string, options v1.GetOptions) (result *v1beta1.ImagePolicyRequirement, err error) {
	result = &v1beta1.ImagePolicyRequirement{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("imagepolicyrequirements").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ImagePolicyRequirements that match those selectors.
func (c *imagePolicyRequirements) List(opts v1.ListOptions) (result *v1beta1.ImagePolicyRequirementList, err error) {
	result = &v1beta1.ImagePolicyRequirementList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("imagepolicyrequirements").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested imagePolicyRequirements.
func (c *imagePolicyRequirements) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("imagepolicyrequirements").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a imagePolicyRequirement and creates it.  Returns the server's representation of the imagePolicyRequirement, and an error, if there is any.
func (c *imagePolicyRequirements) Create(imagePolicyRequirement *v1beta1.ImagePolicyRequirement) (result *v1beta1.ImagePolicyRequirement, err error) {
	result = &v1beta1.ImagePolicyRequirement{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("imagepolicyrequirements").
		Body(imagePolicyRequirement).
		Do().
		Into(result)
	return
}

// Update takes the representation of a imagePolicyRequirement and updates it. Returns the server's representation of the imagePolicyRequirement, and an error, if there is any.
func (c *imagePolicyRequirements) Update(imagePolicyRequirement *v1beta1.ImagePolicyRequirement) (result *v1beta1.ImagePolicyRequirement, err error) {
	result = &v1beta1.ImagePolicyRequirement{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("imagepolicyrequirements").
		Name(imagePolicyRequirement.Name).
		Body(imagePolicyRequirement).
		Do().
		Into(result)
	return
}

// Delete takes name of the imagePolicyRequirement and deletes it. Returns an error if one occurs.
func (c *imagePolicyRequirements) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("imagepolicyrequirements").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *imagePolicyRequirements) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("imagepolicyrequirements").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched imagePolicyRequirement.
func (c *imagePolicyRequirements) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.ImagePolicyRequirement, err error) {
	result = &v1beta1.ImagePolicyRequirement{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("imagepolicyrequirements").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
